name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%234E85BF&color_dots=%231F1F1F,%233A3A3A,%23575757,%23878787,%23F5F5F5
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2389AACC&color_dots=%230A0A0A,%23141414,%231F1F1F,%23575757,%23F5F5F5
            dist/github-contribution-grid-snake.gif?color_snake=%234E85BF&color_dots=%231F1F1F,%233A3A3A,%23575757,%23878787,%23F5F5F5

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
